name: Build APKs

on:
  push:
    tags:
      - "v*"

jobs:
  build-kotlin-android:
    name: Build Kotlin Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate Gradle wrapper
        working-directory: ./kotlin
        run: gradle wrapper --gradle-version 8.10.2

      - name: Build Kotlin Android APK
        working-directory: ./kotlin
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload Kotlin APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-android-apk
          path: kotlin/app/build/outputs/apk/release/*.apk
          retention-days: 30

  create-release:
    name: Create GitHub Release
    needs: [build-kotlin-android]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Kotlin APK
        uses: actions/download-artifact@v4
        with:
          name: kotlin-android-apk
          path: ./artifacts/kotlin/

      - name: Rename APK files
        run: |
          # Get the tag name without 'refs/tags/' prefix
          TAG_NAME=${GITHUB_REF#refs/tags/}

          # Find and rename APK file with descriptive name
          find ./artifacts/kotlin/ -name "*.apk" -exec mv {} ./artifacts/bhittepatro-kotlin-${TAG_NAME}.apk \;

          # List files for verification
          ls -la ./artifacts/

      - name: Extract release notes from tag
        id: release_notes
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT

          # Create release notes (you can customize this)
          cat > release_notes.md << EOF
          # Release ${TAG_NAME}

          ## Downloads
          - bhittepatro-kotlin-${TAG_NAME}.apk

          Built automatically from commit: ${{ github.sha }}
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release_notes.outputs.tag_name }}
          name: Bhittepatro ${{ steps.release_notes.outputs.tag_name }}
          body_path: release_notes.md
          draft: false
          prerelease: false
          files: |
            ./artifacts/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}

  cleanup:
    name: Cleanup Artifacts
    needs: [create-release]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            kotlin-android-apk
